language: python
before_install:
  - sudo add-apt-repository --yes ppa:fontforge/fontforge
  - sudo apt-get update -qq
  - sudo apt-get install fontforge
install:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - pip install python-coveralls
  - "pip install git+https://github.com/behdad/fonttools.git"
  - "pip install git+https://github.com/googlefonts/fontbakery-cli.git"
script: LANG="en" python setup.py nosetests
after_success:
  coveralls
